name: CJS Library Build & Publish

# Need to update this for actual migration.
trigger: none

pr:
  - '*'

resources:
  repositories:
    - repository: travisSettings
      type: github
      name: hmcts/cjs-travis-settings
      endpoint: 'hmcts'
      ref: 'test-new'

pool:
  name: 'MDV-ADO-AGENT-AKS-01'
  demands:
    - identifier -equals simran-temp
variables:
  - group: "cjs-common-platform"

stages:
  - stage: BuildAndPublish
    jobs:
      - job: BuildAndPublish
        timeoutInMinutes: 120
        variables:
          JAVA_TOOL_OPTIONS: '-Dhttps.protocols=TLSv1.2,TLSv1,TLSv1.1'
          PGPORT: 5432
          PGHOST: localhost
        steps:
          - checkout: self
            path: s
          - checkout: travisSettings
            path: s/target/travis-settings
            fetchDepth: 3
          # TODO: Setup PGSQL databases
          - task: bash@3
            displayName: 'Create Postgres Databases'
            inputs:
              failOnStderr: false
              targetType: 'inline'
              script: |
                #!/bin/bash
                psql -V
                psql -c 'CREATE DATABASE frameworkeventstore;' -U postgres
                psql -c 'CREATE DATABASE frameworkviewstore;' -U postgres
                psql -c 'CREATE DATABASE frameworkfilestore;' -U postgres
                psql -c 'CREATE DATABASE frameworkjobstore;' -U postgres
                psql -c "CREATE USER framework WITH PASSWORD 'framework';" -U postgres
                psql -c "GRANT all ON SCHEMA public TO framework;" -d frameworkeventstore -U postgres
                psql -c "GRANT all ON SCHEMA public TO framework;" -d frameworkviewstore -U postgres
                psql -c "GRANT all ON SCHEMA public TO framework;" -d frameworkfilestore -U postgres
                psql -c "GRANT all ON SCHEMA public TO framework;" -d frameworkjobstore -U postgres

          - task: Cache@2
            condition: and(succeeded(), eq(variables.shouldrun, 'true'))
            inputs:
              key: 'maven | "$(Agent.OS)" | **/pom.xml'
              restoreKeys: |
                maven | "$(Agent.OS)"
              path: $(System.DefaultWorkingDirectory)/.m2/repository

          - task: bash@3
            displayName: 'Pre-Install'
            inputs:
              failOnStderr: true
              targetType: 'inline'
              script: |
                #!/bin/bash
                # Symlink cloned travis settings to relevant paths
                echo pwd: $(pwd)
                echo Agentdir: $(Agent.RootDirectory)
                echo Workspace: $(Pipeline.Workspace)
                echo Homedir: $(Agent.HomeDirectory)
                echo Default Workdir: $(System.DefaultWorkingDirectory)
                echo Sourcedir: $(Build.SourcesDirectory)
                mkdir -p ~/.m2/
                cp target/travis-settings/settings.xml ~/.m2/settings.xml
                cp target/travis-settings/mvnw ./mvnw
                cp -r target/travis-settings/.mvn .
                ls -al  
          - task: bash@3
            displayName: 'Install'
            inputs:
              targetType: 'inline'
              script: |
                set -x
                bash target/travis-settings/java/install.sh -e -DexcludeGroupIds=uk.gov.justice.service,uk.gov.justice.services
            env:
              CLOUDSMITH_API_KEY: $(CLOUDSMITH_API_KEY)
              SONARCLOUD_API_KEY: $(SONARCLOUD_API_KEY)
          - task: bash@3
            displayName: 'Test'
            inputs:
              targetType: 'filePath'
              filePath: 'target/travis-settings/java/script-install.sh'
              arguments: 'sonar:sonar -Dsonar.login=$(SONARCLOUD_API_KEY) -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=uk.gov.justice.framework.libraries:framework-libraries -Dsonar.organization=cjscommonplatform coveralls:report -DrepoToken="gjyMlRmiQgtpLBlTSZkf9vB73rJc9WOiX" -Dcoveralls.endpoint="https://coveralls.io/" '
            env:
              CLOUDSMITH_API_KEY: $(CLOUDSMITH_API_KEY)
              SONARCLOUD_API_KEY: $(SONARCLOUD_API_KEY)
          - task: bash@3
            displayName: 'Deploy'
            inputs:
              targetType: 'filePath'
              filePath: 'target/travis-settings/java/after_success.sh'
            env:
              CLOUDSMITH_API_KEY: $(CLOUDSMITH_API_KEY)
              SONARCLOUD_API_KEY: $(SONARCLOUD_API_KEY)